//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_t
    {
        public int Id { get; set; }
        public System.Guid UserUid { get; set; }
        public int DirtionaryId { get; set; }
        public int Times { get; set; }
        public int Groups { get; set; }
    }
}
